SET IDENTITY_INSERT [dbo].[ThresholdAppetites] ON 
GO

DECLARE @ThresholdVeryHigh INT, @ThresholdHigh INT, @ThresholdMedium INT, @ThresholdLow INT, @ThresholdVeryLow INT
SET @ThresholdVeryHigh = (SELECT [ID] FROM [dbo].[Thresholds] WHERE [Title]='Very High')
SET @ThresholdHigh = (SELECT [ID] FROM [dbo].[Thresholds] WHERE [Title]='High')
SET @ThresholdMedium = (SELECT [ID] FROM [dbo].[Thresholds] WHERE [Title]='Medium')
SET @ThresholdLow = (SELECT [ID] FROM [dbo].[Thresholds] WHERE [Title]='Low')
SET @ThresholdVeryLow = (SELECT [ID] FROM [dbo].[Thresholds] WHERE [Title]='Very Low')

DECLARE @ImpactLevelVeryHigh INT, @ImpactLevelHigh INT, @ImpactLevelMedium INT, @ImpactLevelLow INT, @ImpactLevelVeryLow INT
SET @ImpactLevelVeryHigh = (SELECT [ID] FROM [dbo].[RiskImpactLevels] WHERE [Title]='Very High')
SET @ImpactLevelHigh = (SELECT [ID] FROM [dbo].[RiskImpactLevels] WHERE [Title]='High')
SET @ImpactLevelMedium = (SELECT [ID] FROM [dbo].[RiskImpactLevels] WHERE [Title]='Medium')
SET @ImpactLevelLow = (SELECT [ID] FROM [dbo].[RiskImpactLevels] WHERE [Title]='Low')
SET @ImpactLevelVeryLow = (SELECT [ID] FROM [dbo].[RiskImpactLevels] WHERE [Title]='Very Low')

DECLARE @ProbabilityVeryLikely INT, @ProbabilityLikely INT, @ProbabilityPossible INT, @ProbabilityUnlikely INT, @ProbabilityVeryUnlikely INT
SET @ProbabilityVeryLikely = (SELECT [ID] FROM [dbo].[RiskProbabilities] WHERE [Title] LIKE 'Very Likely%' AND [EndUpdatePeriod] IS NULL)
SET @ProbabilityLikely = (SELECT [ID] FROM [dbo].[RiskProbabilities] WHERE [Title] LIKE 'Likely%' AND [EndUpdatePeriod] IS NULL)
SET @ProbabilityPossible = (SELECT [ID] FROM [dbo].[RiskProbabilities] WHERE [Title] LIKE 'Possible%' AND [EndUpdatePeriod] IS NULL)
SET @ProbabilityUnlikely = (SELECT [ID] FROM [dbo].[RiskProbabilities] WHERE [Title] LIKE 'Unlikely%' AND [EndUpdatePeriod] IS NULL)
SET @ProbabilityVeryUnlikely = (SELECT [ID] FROM [dbo].[RiskProbabilities] WHERE [Title] LIKE 'Very Unlikely%' AND [EndUpdatePeriod] IS NULL)

INSERT [dbo].[ThresholdAppetites] ([ID], [ThresholdID], [RiskImpactLevelID], [RiskProbabilityID], [Acceptable]) VALUES (1, @ThresholdHigh, @ImpactLevelMedium, @ProbabilityVeryLikely, 0)
INSERT [dbo].[ThresholdAppetites] ([ID], [ThresholdID], [RiskImpactLevelID], [RiskProbabilityID], [Acceptable]) VALUES (2, @ThresholdHigh, @ImpactLevelHigh, @ProbabilityLikely, 0)
INSERT [dbo].[ThresholdAppetites] ([ID], [ThresholdID], [RiskImpactLevelID], [RiskProbabilityID], [Acceptable]) VALUES (3, @ThresholdHigh, @ImpactLevelVeryHigh, @ProbabilityPossible, 0)
INSERT [dbo].[ThresholdAppetites] ([ID], [ThresholdID], [RiskImpactLevelID], [RiskProbabilityID], [Acceptable]) VALUES (4, @ThresholdVeryHigh, @ImpactLevelVeryHigh, @ProbabilityVeryLikely, 0)
INSERT [dbo].[ThresholdAppetites] ([ID], [ThresholdID], [RiskImpactLevelID], [RiskProbabilityID], [Acceptable]) VALUES (5, @ThresholdLow, @ImpactLevelVeryHigh, @ProbabilityVeryLikely, 0)
INSERT [dbo].[ThresholdAppetites] ([ID], [ThresholdID], [RiskImpactLevelID], [RiskProbabilityID], [Acceptable]) VALUES (6, @ThresholdHigh, @ImpactLevelHigh, @ProbabilityVeryLikely, 0)
INSERT [dbo].[ThresholdAppetites] ([ID], [ThresholdID], [RiskImpactLevelID], [RiskProbabilityID], [Acceptable]) VALUES (7, @ThresholdHigh, @ImpactLevelVeryHigh, @ProbabilityLikely, 0)
INSERT [dbo].[ThresholdAppetites] ([ID], [ThresholdID], [RiskImpactLevelID], [RiskProbabilityID], [Acceptable]) VALUES (8, @ThresholdHigh, @ImpactLevelVeryHigh, @ProbabilityVeryLikely, 0)
INSERT [dbo].[ThresholdAppetites] ([ID], [ThresholdID], [RiskImpactLevelID], [RiskProbabilityID], [Acceptable]) VALUES (9, @ThresholdVeryHigh, @ImpactLevelVeryHigh, @ProbabilityLikely, 0)
INSERT [dbo].[ThresholdAppetites] ([ID], [ThresholdID], [RiskImpactLevelID], [RiskProbabilityID], [Acceptable]) VALUES (10, @ThresholdVeryHigh, @ImpactLevelHigh, @ProbabilityVeryLikely, 0)
INSERT [dbo].[ThresholdAppetites] ([ID], [ThresholdID], [RiskImpactLevelID], [RiskProbabilityID], [Acceptable]) VALUES (11, @ThresholdMedium, @ImpactLevelVeryHigh, @ProbabilityUnlikely, 0)
INSERT [dbo].[ThresholdAppetites] ([ID], [ThresholdID], [RiskImpactLevelID], [RiskProbabilityID], [Acceptable]) VALUES (12, @ThresholdMedium, @ImpactLevelVeryHigh, @ProbabilityPossible, 0)
INSERT [dbo].[ThresholdAppetites] ([ID], [ThresholdID], [RiskImpactLevelID], [RiskProbabilityID], [Acceptable]) VALUES (13, @ThresholdMedium, @ImpactLevelVeryHigh, @ProbabilityLikely, 0)
INSERT [dbo].[ThresholdAppetites] ([ID], [ThresholdID], [RiskImpactLevelID], [RiskProbabilityID], [Acceptable]) VALUES (14, @ThresholdMedium, @ImpactLevelVeryHigh, @ProbabilityVeryLikely, 0)
INSERT [dbo].[ThresholdAppetites] ([ID], [ThresholdID], [RiskImpactLevelID], [RiskProbabilityID], [Acceptable]) VALUES (15, @ThresholdMedium, @ImpactLevelHigh, @ProbabilityPossible, 0)
INSERT [dbo].[ThresholdAppetites] ([ID], [ThresholdID], [RiskImpactLevelID], [RiskProbabilityID], [Acceptable]) VALUES (16, @ThresholdMedium, @ImpactLevelHigh, @ProbabilityLikely, 0)
INSERT [dbo].[ThresholdAppetites] ([ID], [ThresholdID], [RiskImpactLevelID], [RiskProbabilityID], [Acceptable]) VALUES (17, @ThresholdMedium, @ImpactLevelHigh, @ProbabilityVeryLikely, 0)
INSERT [dbo].[ThresholdAppetites] ([ID], [ThresholdID], [RiskImpactLevelID], [RiskProbabilityID], [Acceptable]) VALUES (18, @ThresholdMedium, @ImpactLevelMedium, @ProbabilityLikely, 0)
INSERT [dbo].[ThresholdAppetites] ([ID], [ThresholdID], [RiskImpactLevelID], [RiskProbabilityID], [Acceptable]) VALUES (19, @ThresholdMedium, @ImpactLevelMedium, @ProbabilityVeryLikely, 0)
INSERT [dbo].[ThresholdAppetites] ([ID], [ThresholdID], [RiskImpactLevelID], [RiskProbabilityID], [Acceptable]) VALUES (20, @ThresholdMedium, @ImpactLevelLow, @ProbabilityVeryLikely, 0)
INSERT [dbo].[ThresholdAppetites] ([ID], [ThresholdID], [RiskImpactLevelID], [RiskProbabilityID], [Acceptable]) VALUES (21, @ThresholdLow, @ImpactLevelVeryHigh, @ProbabilityLikely, 0)
INSERT [dbo].[ThresholdAppetites] ([ID], [ThresholdID], [RiskImpactLevelID], [RiskProbabilityID], [Acceptable]) VALUES (22, @ThresholdLow, @ImpactLevelVeryHigh, @ProbabilityPossible, 0)
INSERT [dbo].[ThresholdAppetites] ([ID], [ThresholdID], [RiskImpactLevelID], [RiskProbabilityID], [Acceptable]) VALUES (23, @ThresholdLow, @ImpactLevelVeryHigh, @ProbabilityUnlikely, 0)
INSERT [dbo].[ThresholdAppetites] ([ID], [ThresholdID], [RiskImpactLevelID], [RiskProbabilityID], [Acceptable]) VALUES (24, @ThresholdLow, @ImpactLevelVeryHigh, @ProbabilityVeryUnlikely, 0)
INSERT [dbo].[ThresholdAppetites] ([ID], [ThresholdID], [RiskImpactLevelID], [RiskProbabilityID], [Acceptable]) VALUES (25, @ThresholdLow, @ImpactLevelHigh, @ProbabilityVeryLikely, 0)
INSERT [dbo].[ThresholdAppetites] ([ID], [ThresholdID], [RiskImpactLevelID], [RiskProbabilityID], [Acceptable]) VALUES (26, @ThresholdLow, @ImpactLevelHigh, @ProbabilityLikely, 0)
INSERT [dbo].[ThresholdAppetites] ([ID], [ThresholdID], [RiskImpactLevelID], [RiskProbabilityID], [Acceptable]) VALUES (27, @ThresholdLow, @ImpactLevelHigh, @ProbabilityPossible, 0)
INSERT [dbo].[ThresholdAppetites] ([ID], [ThresholdID], [RiskImpactLevelID], [RiskProbabilityID], [Acceptable]) VALUES (28, @ThresholdLow, @ImpactLevelHigh, @ProbabilityUnlikely, 0)
INSERT [dbo].[ThresholdAppetites] ([ID], [ThresholdID], [RiskImpactLevelID], [RiskProbabilityID], [Acceptable]) VALUES (29, @ThresholdLow, @ImpactLevelMedium, @ProbabilityVeryLikely, 0)
INSERT [dbo].[ThresholdAppetites] ([ID], [ThresholdID], [RiskImpactLevelID], [RiskProbabilityID], [Acceptable]) VALUES (30, @ThresholdLow, @ImpactLevelMedium, @ProbabilityLikely, 0)
INSERT [dbo].[ThresholdAppetites] ([ID], [ThresholdID], [RiskImpactLevelID], [RiskProbabilityID], [Acceptable]) VALUES (31, @ThresholdLow, @ImpactLevelMedium, @ProbabilityPossible, 0)
INSERT [dbo].[ThresholdAppetites] ([ID], [ThresholdID], [RiskImpactLevelID], [RiskProbabilityID], [Acceptable]) VALUES (32, @ThresholdLow, @ImpactLevelMedium, @ProbabilityUnlikely, 0)
INSERT [dbo].[ThresholdAppetites] ([ID], [ThresholdID], [RiskImpactLevelID], [RiskProbabilityID], [Acceptable]) VALUES (33, @ThresholdLow, @ImpactLevelLow, @ProbabilityVeryLikely, 0)
INSERT [dbo].[ThresholdAppetites] ([ID], [ThresholdID], [RiskImpactLevelID], [RiskProbabilityID], [Acceptable]) VALUES (34, @ThresholdLow, @ImpactLevelLow, @ProbabilityLikely, 0)
INSERT [dbo].[ThresholdAppetites] ([ID], [ThresholdID], [RiskImpactLevelID], [RiskProbabilityID], [Acceptable]) VALUES (35, @ThresholdLow, @ImpactLevelLow, @ProbabilityPossible, 0)
INSERT [dbo].[ThresholdAppetites] ([ID], [ThresholdID], [RiskImpactLevelID], [RiskProbabilityID], [Acceptable]) VALUES (36, @ThresholdLow, @ImpactLevelVeryLow, @ProbabilityVeryLikely, 0)
INSERT [dbo].[ThresholdAppetites] ([ID], [ThresholdID], [RiskImpactLevelID], [RiskProbabilityID], [Acceptable]) VALUES (37, @ThresholdVeryLow, @ImpactLevelVeryHigh, @ProbabilityVeryLikely, 0)
INSERT [dbo].[ThresholdAppetites] ([ID], [ThresholdID], [RiskImpactLevelID], [RiskProbabilityID], [Acceptable]) VALUES (38, @ThresholdVeryLow, @ImpactLevelVeryHigh, @ProbabilityLikely, 0)
INSERT [dbo].[ThresholdAppetites] ([ID], [ThresholdID], [RiskImpactLevelID], [RiskProbabilityID], [Acceptable]) VALUES (39, @ThresholdVeryLow, @ImpactLevelVeryHigh, @ProbabilityPossible, 0)
INSERT [dbo].[ThresholdAppetites] ([ID], [ThresholdID], [RiskImpactLevelID], [RiskProbabilityID], [Acceptable]) VALUES (40, @ThresholdVeryLow, @ImpactLevelVeryHigh, @ProbabilityUnlikely, 0)
INSERT [dbo].[ThresholdAppetites] ([ID], [ThresholdID], [RiskImpactLevelID], [RiskProbabilityID], [Acceptable]) VALUES (41, @ThresholdVeryLow, @ImpactLevelVeryHigh, @ProbabilityVeryUnlikely, 0)
INSERT [dbo].[ThresholdAppetites] ([ID], [ThresholdID], [RiskImpactLevelID], [RiskProbabilityID], [Acceptable]) VALUES (42, @ThresholdVeryLow, @ImpactLevelHigh, @ProbabilityVeryLikely, 0)
INSERT [dbo].[ThresholdAppetites] ([ID], [ThresholdID], [RiskImpactLevelID], [RiskProbabilityID], [Acceptable]) VALUES (43, @ThresholdVeryLow, @ImpactLevelHigh, @ProbabilityLikely, 0)
INSERT [dbo].[ThresholdAppetites] ([ID], [ThresholdID], [RiskImpactLevelID], [RiskProbabilityID], [Acceptable]) VALUES (44, @ThresholdVeryLow, @ImpactLevelHigh, @ProbabilityPossible, 0)
INSERT [dbo].[ThresholdAppetites] ([ID], [ThresholdID], [RiskImpactLevelID], [RiskProbabilityID], [Acceptable]) VALUES (45, @ThresholdVeryLow, @ImpactLevelHigh, @ProbabilityUnlikely, 0)
INSERT [dbo].[ThresholdAppetites] ([ID], [ThresholdID], [RiskImpactLevelID], [RiskProbabilityID], [Acceptable]) VALUES (46, @ThresholdVeryLow, @ImpactLevelHigh, @ProbabilityVeryUnlikely, 0)
INSERT [dbo].[ThresholdAppetites] ([ID], [ThresholdID], [RiskImpactLevelID], [RiskProbabilityID], [Acceptable]) VALUES (47, @ThresholdVeryLow, @ImpactLevelMedium, @ProbabilityVeryLikely, 0)
INSERT [dbo].[ThresholdAppetites] ([ID], [ThresholdID], [RiskImpactLevelID], [RiskProbabilityID], [Acceptable]) VALUES (48, @ThresholdVeryLow, @ImpactLevelMedium, @ProbabilityLikely, 0)
INSERT [dbo].[ThresholdAppetites] ([ID], [ThresholdID], [RiskImpactLevelID], [RiskProbabilityID], [Acceptable]) VALUES (49, @ThresholdVeryLow, @ImpactLevelMedium, @ProbabilityPossible, 0)
INSERT [dbo].[ThresholdAppetites] ([ID], [ThresholdID], [RiskImpactLevelID], [RiskProbabilityID], [Acceptable]) VALUES (50, @ThresholdVeryLow, @ImpactLevelMedium, @ProbabilityUnlikely, 0)
INSERT [dbo].[ThresholdAppetites] ([ID], [ThresholdID], [RiskImpactLevelID], [RiskProbabilityID], [Acceptable]) VALUES (51, @ThresholdVeryLow, @ImpactLevelMedium, @ProbabilityVeryUnlikely, 0)
INSERT [dbo].[ThresholdAppetites] ([ID], [ThresholdID], [RiskImpactLevelID], [RiskProbabilityID], [Acceptable]) VALUES (52, @ThresholdVeryLow, @ImpactLevelLow, @ProbabilityVeryLikely, 0)
INSERT [dbo].[ThresholdAppetites] ([ID], [ThresholdID], [RiskImpactLevelID], [RiskProbabilityID], [Acceptable]) VALUES (53, @ThresholdVeryLow, @ImpactLevelLow, @ProbabilityLikely, 0)
INSERT [dbo].[ThresholdAppetites] ([ID], [ThresholdID], [RiskImpactLevelID], [RiskProbabilityID], [Acceptable]) VALUES (54, @ThresholdVeryLow, @ImpactLevelLow, @ProbabilityPossible, 0)
INSERT [dbo].[ThresholdAppetites] ([ID], [ThresholdID], [RiskImpactLevelID], [RiskProbabilityID], [Acceptable]) VALUES (55, @ThresholdVeryLow, @ImpactLevelLow, @ProbabilityUnlikely, 0)
INSERT [dbo].[ThresholdAppetites] ([ID], [ThresholdID], [RiskImpactLevelID], [RiskProbabilityID], [Acceptable]) VALUES (56, @ThresholdVeryLow, @ImpactLevelVeryLow, @ProbabilityVeryLikely, 0)
INSERT [dbo].[ThresholdAppetites] ([ID], [ThresholdID], [RiskImpactLevelID], [RiskProbabilityID], [Acceptable]) VALUES (57, @ThresholdVeryLow, @ImpactLevelVeryLow, @ProbabilityLikely, 0)
INSERT [dbo].[ThresholdAppetites] ([ID], [ThresholdID], [RiskImpactLevelID], [RiskProbabilityID], [Acceptable]) VALUES (58, @ThresholdVeryLow, @ImpactLevelVeryLow, @ProbabilityPossible, 0)

SET IDENTITY_INSERT [dbo].[ThresholdAppetites] OFF
GO
