CREATE TABLE [dbo].[RiskTypes]
(
	[ID] INT IDENTITY(1,1) NOT NULL,
	[Title] NVARCHAR(50) NULL,
	[ThresholdID] INT NULL,
	CONSTRAINT [PK_RiskImpactTypes] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[RiskTypes]  ADD  CONSTRAINT [FK_RiskTypes_Thresholds] FOREIGN KEY([ThresholdID])
REFERENCES [dbo].[Thresholds] ([ID])
GO
ALTER TABLE [dbo].[RiskTypes] CHECK CONSTRAINT [FK_RiskTypes_Thresholds]
GO