namespace ORB.Core
{
    public enum ReportingDueDays
    {
        D0, // Sunday
        D1, // Monday or 1st of month
        D2, // Tuesday or 2nd of month
        D3, // Wednesday or 3rd of month
        D4, // Thursday or 4th of month
        D5, // Friday or 5th of month
        D6, // Saturday or 6th of month
        D7,
        D8,
        D9,
        D10,
        D11,
        D12,
        D13,
        D14,
        D15,
        D16,
        D17,
        D18,
        D19,
        D20,
        D21,
        D22,
        D23,
        D24,
        D25,
        D26,
        D27,
        D28,
        D29,
        D30,
        D31,
        DayBeforeLast = 99,
        LastDay = 100,
        FirstSunday = 110,
        FirstMonday,
        FirstTuesday,
        FirstWednesday,
        FirstThursday,
        FirstFriday,
        FirstSaturday,
        SecondSunday = 120,
        SecondMonday,
        SecondTuesday,
        SecondWednesday,
        SecondThursday,
        SecondFriday,
        SecondSaturday,
        ThirdSunday = 130,
        ThirdMonday,
        ThirdTuesday,
        ThirdWednesday,
        ThirdThursday,
        ThirdFriday,
        ThirdSaturday,
        FourthSunday = 140,
        FourthMonday,
        FourthTuesday,
        FourthWednesday,
        FourthThursday,
        FourthFriday,
        FourthSaturday,
        LastSunday = 150,
        LastMonday,
        LastTuesday,
        LastWednesday,
        LastThursday,
        LastFriday,
        LastSaturday
    }
}