#!/bin/bash

######################################################################################################
# Script: reset-sql-admin-password
#
# This script changes the SQL Admin password for the Corporate Reporting SQL database for the given environment
#
# The script requires the following environment variables to be set:
#
#     env - The environment name
#     adminPassword - The new admin password
######################################################################################################

usage='Usage - ./reset-sql-admin-password <environment> <adminPassword>'
env=${1?$usage}
adminPassword=${2?$usage}

# Set-up common resource names (execute in current shell)
. set-resource-names $env

if az sql server show --name $sqlInstanceName --resource-group $resourceGroupName
then
    echo "Changing SQL Admin password..."

    az sql server update --name $sqlInstanceName --resource-group $resourceGroupName --admin-password $adminPassword
else
    echo "SQL Azure Database Server does not exist - no action required"
fi

echo "Complete."
